// Code generated by Fern. DO NOT EDIT.

package client

import (
	context "context"
	http "net/http"

	coherego "github.com/cohere-ai/cohere-go"
	core "github.com/cohere-ai/cohere-go/core"
	internal "github.com/cohere-ai/cohere-go/internal"
	option "github.com/cohere-ai/cohere-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) Chat(
	ctx context.Context,
	request *coherego.ChatRequest,
	opts ...option.RequestOption,
) (*core.Response[*coherego.NonStreamedChatResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.cohere.com",
	)
	endpointURL := baseURL + "/v1/chat"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.Accepts != nil {
		headers.Add("Accepts", *request.Accepts)
	}
	headers.Add("Content-Type", "application/json")
	var response *coherego.NonStreamedChatResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coherego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coherego.NonStreamedChatResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Generate(
	ctx context.Context,
	request *coherego.GenerateRequest,
	opts ...option.RequestOption,
) (*core.Response[*coherego.Generation], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.cohere.com",
	)
	endpointURL := baseURL + "/v1/generate"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *coherego.Generation
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coherego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coherego.Generation]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Embed(
	ctx context.Context,
	request *coherego.EmbedRequest,
	opts ...option.RequestOption,
) (*core.Response[*coherego.EmbedResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.cohere.com",
	)
	endpointURL := baseURL + "/v1/embed"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *coherego.EmbedResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coherego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coherego.EmbedResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Rerank(
	ctx context.Context,
	request *coherego.RerankRequest,
	opts ...option.RequestOption,
) (*core.Response[*coherego.RerankResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.cohere.com",
	)
	endpointURL := baseURL + "/v1/rerank"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *coherego.RerankResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coherego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coherego.RerankResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Classify(
	ctx context.Context,
	request *coherego.ClassifyRequest,
	opts ...option.RequestOption,
) (*core.Response[*coherego.ClassifyResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.cohere.com",
	)
	endpointURL := baseURL + "/v1/classify"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *coherego.ClassifyResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coherego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coherego.ClassifyResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Summarize(
	ctx context.Context,
	request *coherego.SummarizeRequest,
	opts ...option.RequestOption,
) (*core.Response[*coherego.SummarizeResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.cohere.com",
	)
	endpointURL := baseURL + "/v1/summarize"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *coherego.SummarizeResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coherego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coherego.SummarizeResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Tokenize(
	ctx context.Context,
	request *coherego.TokenizeRequest,
	opts ...option.RequestOption,
) (*core.Response[*coherego.TokenizeResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.cohere.com",
	)
	endpointURL := baseURL + "/v1/tokenize"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *coherego.TokenizeResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coherego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coherego.TokenizeResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Detokenize(
	ctx context.Context,
	request *coherego.DetokenizeRequest,
	opts ...option.RequestOption,
) (*core.Response[*coherego.DetokenizeResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.cohere.com",
	)
	endpointURL := baseURL + "/v1/detokenize"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *coherego.DetokenizeResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coherego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coherego.DetokenizeResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) CheckApiKey(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*coherego.CheckApiKeyResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.cohere.com",
	)
	endpointURL := baseURL + "/v1/check-api-key"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *coherego.CheckApiKeyResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(coherego.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*coherego.CheckApiKeyResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
