// Code generated by Fern. DO NOT EDIT.

package transcriptions

import (
	context "context"
	fmt "fmt"
	audio "github.com/cohere-ai/cohere-go/v2/audio"
	core "github.com/cohere-ai/cohere-go/v2/core"
	internal "github.com/cohere-ai/cohere-go/v2/internal"
	option "github.com/cohere-ai/cohere-go/v2/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) Create(
	ctx context.Context,
	request *audio.TranscriptionsCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*audio.AudioTranscriptionsCreateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.cohere.com",
	)
	endpointURL := baseURL + "/v2/audio/transcriptions"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	writer := internal.NewMultipartWriter()
	if err := writer.WriteField("model", request.Model); err != nil {
		return nil, err
	}
	if err := writer.WriteField("language", request.Language); err != nil {
		return nil, err
	}
	if request.Temperature != nil {
		if err := writer.WriteField("temperature", fmt.Sprintf("%v", *request.Temperature)); err != nil {
			return nil, err
		}
	}
	if err := writer.WriteFile("file", request.File); err != nil {
		return nil, err
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	headers.Set("Content-Type", writer.ContentType())

	var response *audio.AudioTranscriptionsCreateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         writer.Buffer(),
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(audio.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*audio.AudioTranscriptionsCreateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
