// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersModelsListRequest(t *testing.T) {
	t.Run("SetPageSize", func(t *testing.T) {
		obj := &ModelsListRequest{}
		var fernTestValuePageSize *float64
		obj.SetPageSize(fernTestValuePageSize)
		assert.Equal(t, fernTestValuePageSize, obj.PageSize)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPageToken", func(t *testing.T) {
		obj := &ModelsListRequest{}
		var fernTestValuePageToken *string
		obj.SetPageToken(fernTestValuePageToken)
		assert.Equal(t, fernTestValuePageToken, obj.PageToken)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndpoint", func(t *testing.T) {
		obj := &ModelsListRequest{}
		var fernTestValueEndpoint *CompatibleEndpoint
		obj.SetEndpoint(fernTestValueEndpoint)
		assert.Equal(t, fernTestValueEndpoint, obj.Endpoint)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDefaultOnly", func(t *testing.T) {
		obj := &ModelsListRequest{}
		var fernTestValueDefaultOnly *bool
		obj.SetDefaultOnly(fernTestValueDefaultOnly)
		assert.Equal(t, fernTestValueDefaultOnly, obj.DefaultOnly)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitModelsListRequest(t *testing.T) {
	t.Run("SetPageSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ModelsListRequest{}
		var fernTestValuePageSize *float64

		// Act
		obj.SetPageSize(fernTestValuePageSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPageToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ModelsListRequest{}
		var fernTestValuePageToken *string

		// Act
		obj.SetPageToken(fernTestValuePageToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndpoint_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ModelsListRequest{}
		var fernTestValueEndpoint *CompatibleEndpoint

		// Act
		obj.SetEndpoint(fernTestValueEndpoint)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDefaultOnly_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ModelsListRequest{}
		var fernTestValueDefaultOnly *bool

		// Act
		obj.SetDefaultOnly(fernTestValueDefaultOnly)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetModelResponse(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &GetModelResponse{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsDeprecated", func(t *testing.T) {
		obj := &GetModelResponse{}
		var fernTestValueIsDeprecated *bool
		obj.SetIsDeprecated(fernTestValueIsDeprecated)
		assert.Equal(t, fernTestValueIsDeprecated, obj.IsDeprecated)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndpoints", func(t *testing.T) {
		obj := &GetModelResponse{}
		var fernTestValueEndpoints []CompatibleEndpoint
		obj.SetEndpoints(fernTestValueEndpoints)
		assert.Equal(t, fernTestValueEndpoints, obj.Endpoints)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFinetuned", func(t *testing.T) {
		obj := &GetModelResponse{}
		var fernTestValueFinetuned *bool
		obj.SetFinetuned(fernTestValueFinetuned)
		assert.Equal(t, fernTestValueFinetuned, obj.Finetuned)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetContextLength", func(t *testing.T) {
		obj := &GetModelResponse{}
		var fernTestValueContextLength *float64
		obj.SetContextLength(fernTestValueContextLength)
		assert.Equal(t, fernTestValueContextLength, obj.ContextLength)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTokenizerUrl", func(t *testing.T) {
		obj := &GetModelResponse{}
		var fernTestValueTokenizerUrl *string
		obj.SetTokenizerUrl(fernTestValueTokenizerUrl)
		assert.Equal(t, fernTestValueTokenizerUrl, obj.TokenizerUrl)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDefaultEndpoints", func(t *testing.T) {
		obj := &GetModelResponse{}
		var fernTestValueDefaultEndpoints []CompatibleEndpoint
		obj.SetDefaultEndpoints(fernTestValueDefaultEndpoints)
		assert.Equal(t, fernTestValueDefaultEndpoints, obj.DefaultEndpoints)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFeatures", func(t *testing.T) {
		obj := &GetModelResponse{}
		var fernTestValueFeatures []string
		obj.SetFeatures(fernTestValueFeatures)
		assert.Equal(t, fernTestValueFeatures, obj.Features)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetModelResponse(t *testing.T) {
	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetModelResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetIsDeprecated", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var expected *bool
		obj.IsDeprecated = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsDeprecated(), "getter should return the property value")
	})

	t.Run("GetIsDeprecated_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		obj.IsDeprecated = nil

		// Act & Assert
		assert.Nil(t, obj.GetIsDeprecated(), "getter should return nil when property is nil")
	})

	t.Run("GetIsDeprecated_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetModelResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsDeprecated() // Should return zero value
	})

	t.Run("GetEndpoints", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var expected []CompatibleEndpoint
		obj.Endpoints = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEndpoints(), "getter should return the property value")
	})

	t.Run("GetEndpoints_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		obj.Endpoints = nil

		// Act & Assert
		assert.Nil(t, obj.GetEndpoints(), "getter should return nil when property is nil")
	})

	t.Run("GetEndpoints_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetModelResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEndpoints() // Should return zero value
	})

	t.Run("GetFinetuned", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var expected *bool
		obj.Finetuned = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFinetuned(), "getter should return the property value")
	})

	t.Run("GetFinetuned_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		obj.Finetuned = nil

		// Act & Assert
		assert.Nil(t, obj.GetFinetuned(), "getter should return nil when property is nil")
	})

	t.Run("GetFinetuned_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetModelResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFinetuned() // Should return zero value
	})

	t.Run("GetContextLength", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var expected *float64
		obj.ContextLength = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetContextLength(), "getter should return the property value")
	})

	t.Run("GetContextLength_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		obj.ContextLength = nil

		// Act & Assert
		assert.Nil(t, obj.GetContextLength(), "getter should return nil when property is nil")
	})

	t.Run("GetContextLength_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetModelResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetContextLength() // Should return zero value
	})

	t.Run("GetTokenizerUrl", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var expected *string
		obj.TokenizerUrl = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTokenizerUrl(), "getter should return the property value")
	})

	t.Run("GetTokenizerUrl_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		obj.TokenizerUrl = nil

		// Act & Assert
		assert.Nil(t, obj.GetTokenizerUrl(), "getter should return nil when property is nil")
	})

	t.Run("GetTokenizerUrl_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetModelResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTokenizerUrl() // Should return zero value
	})

	t.Run("GetDefaultEndpoints", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var expected []CompatibleEndpoint
		obj.DefaultEndpoints = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDefaultEndpoints(), "getter should return the property value")
	})

	t.Run("GetDefaultEndpoints_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		obj.DefaultEndpoints = nil

		// Act & Assert
		assert.Nil(t, obj.GetDefaultEndpoints(), "getter should return nil when property is nil")
	})

	t.Run("GetDefaultEndpoints_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetModelResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDefaultEndpoints() // Should return zero value
	})

	t.Run("GetFeatures", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var expected []string
		obj.Features = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFeatures(), "getter should return the property value")
	})

	t.Run("GetFeatures_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		obj.Features = nil

		// Act & Assert
		assert.Nil(t, obj.GetFeatures(), "getter should return nil when property is nil")
	})

	t.Run("GetFeatures_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetModelResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFeatures() // Should return zero value
	})

}

func TestSettersMarkExplicitGetModelResponse(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsDeprecated_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var fernTestValueIsDeprecated *bool

		// Act
		obj.SetIsDeprecated(fernTestValueIsDeprecated)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndpoints_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var fernTestValueEndpoints []CompatibleEndpoint

		// Act
		obj.SetEndpoints(fernTestValueEndpoints)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFinetuned_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var fernTestValueFinetuned *bool

		// Act
		obj.SetFinetuned(fernTestValueFinetuned)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetContextLength_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var fernTestValueContextLength *float64

		// Act
		obj.SetContextLength(fernTestValueContextLength)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTokenizerUrl_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var fernTestValueTokenizerUrl *string

		// Act
		obj.SetTokenizerUrl(fernTestValueTokenizerUrl)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDefaultEndpoints_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var fernTestValueDefaultEndpoints []CompatibleEndpoint

		// Act
		obj.SetDefaultEndpoints(fernTestValueDefaultEndpoints)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFeatures_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}
		var fernTestValueFeatures []string

		// Act
		obj.SetFeatures(fernTestValueFeatures)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListModelsResponse(t *testing.T) {
	t.Run("SetModels", func(t *testing.T) {
		obj := &ListModelsResponse{}
		var fernTestValueModels []*GetModelResponse
		obj.SetModels(fernTestValueModels)
		assert.Equal(t, fernTestValueModels, obj.Models)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNextPageToken", func(t *testing.T) {
		obj := &ListModelsResponse{}
		var fernTestValueNextPageToken *string
		obj.SetNextPageToken(fernTestValueNextPageToken)
		assert.Equal(t, fernTestValueNextPageToken, obj.NextPageToken)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListModelsResponse(t *testing.T) {
	t.Run("GetModels", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListModelsResponse{}
		var expected []*GetModelResponse
		obj.Models = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetModels(), "getter should return the property value")
	})

	t.Run("GetModels_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListModelsResponse{}
		obj.Models = nil

		// Act & Assert
		assert.Nil(t, obj.GetModels(), "getter should return nil when property is nil")
	})

	t.Run("GetModels_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListModelsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetModels() // Should return zero value
	})

	t.Run("GetNextPageToken", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListModelsResponse{}
		var expected *string
		obj.NextPageToken = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNextPageToken(), "getter should return the property value")
	})

	t.Run("GetNextPageToken_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListModelsResponse{}
		obj.NextPageToken = nil

		// Act & Assert
		assert.Nil(t, obj.GetNextPageToken(), "getter should return nil when property is nil")
	})

	t.Run("GetNextPageToken_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListModelsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNextPageToken() // Should return zero value
	})

}

func TestSettersMarkExplicitListModelsResponse(t *testing.T) {
	t.Run("SetModels_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListModelsResponse{}
		var fernTestValueModels []*GetModelResponse

		// Act
		obj.SetModels(fernTestValueModels)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNextPageToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListModelsResponse{}
		var fernTestValueNextPageToken *string

		// Act
		obj.SetNextPageToken(fernTestValueNextPageToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingGetModelResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetModelResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetModelResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetModelResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetModelResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListModelsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListModelsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListModelsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListModelsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListModelsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringGetModelResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetModelResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetModelResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListModelsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListModelsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListModelsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumCompatibleEndpoint(t *testing.T) {
	t.Run("NewFromString_chat", func(t *testing.T) {
		t.Parallel()
		val, err := NewCompatibleEndpointFromString("chat")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CompatibleEndpoint("chat"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_embed", func(t *testing.T) {
		t.Parallel()
		val, err := NewCompatibleEndpointFromString("embed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CompatibleEndpoint("embed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_classify", func(t *testing.T) {
		t.Parallel()
		val, err := NewCompatibleEndpointFromString("classify")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CompatibleEndpoint("classify"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_summarize", func(t *testing.T) {
		t.Parallel()
		val, err := NewCompatibleEndpointFromString("summarize")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CompatibleEndpoint("summarize"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_rerank", func(t *testing.T) {
		t.Parallel()
		val, err := NewCompatibleEndpointFromString("rerank")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CompatibleEndpoint("rerank"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_rate", func(t *testing.T) {
		t.Parallel()
		val, err := NewCompatibleEndpointFromString("rate")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CompatibleEndpoint("rate"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_generate", func(t *testing.T) {
		t.Parallel()
		val, err := NewCompatibleEndpointFromString("generate")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CompatibleEndpoint("generate"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCompatibleEndpointFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCompatibleEndpointFromString("chat")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesGetModelResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetModelResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetModelResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListModelsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListModelsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListModelsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
