// Code generated by Fern. DO NOT EDIT.

package v_2_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	v2 "github.com/cohere-ai/cohere-go/v2"
	client "github.com/cohere-ai/cohere-go/v2/client"
	option "github.com/cohere-ai/cohere-go/v2/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestV2ChatStreamWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.V2ChatStreamRequest{
		Model: "command-a-03-2025",
		Messages: []*v2.ChatMessageV2{
			&v2.ChatMessageV2{
				User: &v2.UserMessageV2{
					Content: &v2.UserMessageV2Content{
						String: "Tell me about LLMs",
					},
				},
			},
		},
	}
	_, invocationErr := client.V2.ChatStream(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/chat", nil, 1)
}

func TestV2ChatStreamWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.V2ChatStreamRequest{
		Model: "command-a-03-2025",
		Messages: []*v2.ChatMessageV2{
			&v2.ChatMessageV2{
				User: &v2.UserMessageV2{
					Content: &v2.UserMessageV2Content{
						String: "Tell me about LLMs",
					},
				},
			},
		},
	}
	_, invocationErr := client.V2.ChatStream(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/chat", nil, 1)
}

func TestV2EmbedWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.V2EmbedRequest{
		Texts: []string{
			"hello",
			"goodbye",
		},
		Model:     "embed-v4.0",
		InputType: v2.EmbedInputTypeClassification,
		EmbeddingTypes: []v2.EmbeddingType{
			v2.EmbeddingTypeFloat,
		},
	}
	_, invocationErr := client.V2.Embed(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/embed", nil, 1)
}

func TestV2RerankWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.V2RerankRequest{
		Documents: []string{
			"Carson City is the capital city of the American state of Nevada.",
			"The Commonwealth of the Northern Mariana Islands is a group of islands in the Pacific Ocean. Its capital is Saipan.",
			"Capitalization or capitalisation in English grammar is the use of a capital letter at the start of a word. English usage varies from capitalization in other languages.",
			"Washington, D.C. (also known as simply Washington or D.C., and officially as the District of Columbia) is the capital of the United States. It is a federal district.",
			"Capital punishment has existed in the United States since beforethe United States was a country. As of 2017, capital punishment is legal in 30 of the 50 states.",
		},
		Query: "What is the capital of the United States?",
		TopN: v2.Int(
			3,
		),
		Model: "rerank-v3.5",
	}
	_, invocationErr := client.V2.Rerank(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v2/rerank", nil, 1)
}
