// Code generated by Fern. DO NOT EDIT.

package finetuning_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	coherego "github.com/cohere-ai/cohere-go"
	client "github.com/cohere-ai/cohere-go/client"
	finetuning "github.com/cohere-ai/cohere-go/finetuning"
	option "github.com/cohere-ai/cohere-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestFinetuningListFinetunedModelsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &coherego.FinetuningListFinetunedModelsRequest{
		PageSize: coherego.Int(
			1,
		),
		PageToken: coherego.String(
			"page_token",
		),
		OrderBy: coherego.String(
			"order_by",
		),
	}
	_, invocationErr := client.Finetuning.ListFinetunedModels(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFinetuningListFinetunedModelsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFinetuningListFinetunedModelsWithWireMock", "GET", "/v1/finetuning/finetuned-models", map[string]string{"page_size": "1", "page_token": "page_token", "order_by": "order_by"}, 1)
}

func TestFinetuningCreateFinetunedModelWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &finetuning.FinetunedModel{
		Name: "name",
		Settings: &finetuning.Settings{
			BaseModel: &finetuning.BaseModel{
				BaseType: finetuning.BaseTypeBaseTypeUnspecified,
			},
			DatasetId: "dataset_id",
		},
	}
	_, invocationErr := client.Finetuning.CreateFinetunedModel(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFinetuningCreateFinetunedModelWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFinetuningCreateFinetunedModelWithWireMock", "POST", "/v1/finetuning/finetuned-models", nil, 1)
}

func TestFinetuningGetFinetunedModelWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Finetuning.GetFinetunedModel(
		context.TODO(),
		"id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFinetuningGetFinetunedModelWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFinetuningGetFinetunedModelWithWireMock", "GET", "/v1/finetuning/finetuned-models/id", nil, 1)
}

func TestFinetuningDeleteFinetunedModelWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Finetuning.DeleteFinetunedModel(
		context.TODO(),
		"id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFinetuningDeleteFinetunedModelWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFinetuningDeleteFinetunedModelWithWireMock", "DELETE", "/v1/finetuning/finetuned-models/id", nil, 1)
}

func TestFinetuningUpdateFinetunedModelWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &coherego.FinetuningUpdateFinetunedModelRequest{
		Name: "name",
		Settings: &finetuning.Settings{
			BaseModel: &finetuning.BaseModel{
				BaseType: finetuning.BaseTypeBaseTypeUnspecified,
			},
			DatasetId: "dataset_id",
		},
	}
	_, invocationErr := client.Finetuning.UpdateFinetunedModel(
		context.TODO(),
		"id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFinetuningUpdateFinetunedModelWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFinetuningUpdateFinetunedModelWithWireMock", "PATCH", "/v1/finetuning/finetuned-models/id", nil, 1)
}

func TestFinetuningListEventsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &coherego.FinetuningListEventsRequest{
		PageSize: coherego.Int(
			1,
		),
		PageToken: coherego.String(
			"page_token",
		),
		OrderBy: coherego.String(
			"order_by",
		),
	}
	_, invocationErr := client.Finetuning.ListEvents(
		context.TODO(),
		"finetuned_model_id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFinetuningListEventsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFinetuningListEventsWithWireMock", "GET", "/v1/finetuning/finetuned-models/finetuned_model_id/events", map[string]string{"page_size": "1", "page_token": "page_token", "order_by": "order_by"}, 1)
}

func TestFinetuningListTrainingStepMetricsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &coherego.FinetuningListTrainingStepMetricsRequest{
		PageSize: coherego.Int(
			1,
		),
		PageToken: coherego.String(
			"page_token",
		),
	}
	_, invocationErr := client.Finetuning.ListTrainingStepMetrics(
		context.TODO(),
		"finetuned_model_id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestFinetuningListTrainingStepMetricsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestFinetuningListTrainingStepMetricsWithWireMock", "GET", "/v1/finetuning/finetuned-models/finetuned_model_id/training-step-metrics", map[string]string{"page_size": "1", "page_token": "page_token"}, 1)
}
