// Code generated by Fern. DO NOT EDIT.

package root_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	v2 "github.com/cohere-ai/cohere-go/v2"
	client "github.com/cohere-ai/cohere-go/v2/client"
	option "github.com/cohere-ai/cohere-go/v2/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestChatStreamWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.ChatStreamRequest{
		Model: v2.String(
			"command-a-03-2025",
		),
		Message: "hello!",
	}
	_, invocationErr := client.ChatStream(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/chat", nil, 1)
}

func TestChatStreamWithWireMock2(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.ChatStreamRequest{
		Model: v2.String(
			"command-a-03-2025",
		),
		Message: "Tell me about LLMs",
	}
	_, invocationErr := client.ChatStream(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/chat", nil, 1)
}

func TestGenerateStreamWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.GenerateStreamRequest{
		Prompt: "Please explain to me how LLMs work",
	}
	_, invocationErr := client.GenerateStream(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/generate", nil, 1)
}

func TestGenerateStreamWithWireMock2(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.GenerateStreamRequest{
		Prompt: "Please explain to me how LLMs work",
	}
	_, invocationErr := client.GenerateStream(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/generate", nil, 1)
}

func TestEmbedWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.EmbedRequest{
		Texts: []string{
			"hello",
			"goodbye",
		},
		Model: v2.String(
			"embed-v4.0",
		),
		InputType: v2.EmbedInputTypeClassification.Ptr(),
	}
	_, invocationErr := client.Embed(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/embed", nil, 1)
}

func TestRerankWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.RerankRequest{
		Documents: []*v2.RerankRequestDocumentsItem{
			&v2.RerankRequestDocumentsItem{},
			&v2.RerankRequestDocumentsItem{},
			&v2.RerankRequestDocumentsItem{},
			&v2.RerankRequestDocumentsItem{},
			&v2.RerankRequestDocumentsItem{},
		},
		Query: "What is the capital of the United States?",
		TopN: v2.Int(
			3,
		),
		Model: v2.String(
			"rerank-v4.0-pro",
		),
	}
	_, invocationErr := client.Rerank(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/rerank", nil, 1)
}

func TestClassifyWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.ClassifyRequest{
		Examples: []*v2.ClassifyExample{
			&v2.ClassifyExample{
				Text: v2.String(
					"Dermatologists don't like her!",
				),
				Label: v2.String(
					"Spam",
				),
			},
			&v2.ClassifyExample{
				Text: v2.String(
					"'Hello, open to this?'",
				),
				Label: v2.String(
					"Spam",
				),
			},
			&v2.ClassifyExample{
				Text: v2.String(
					"I need help please wire me $1000 right now",
				),
				Label: v2.String(
					"Spam",
				),
			},
			&v2.ClassifyExample{
				Text: v2.String(
					"Nice to know you ;)",
				),
				Label: v2.String(
					"Spam",
				),
			},
			&v2.ClassifyExample{
				Text: v2.String(
					"Please help me?",
				),
				Label: v2.String(
					"Spam",
				),
			},
			&v2.ClassifyExample{
				Text: v2.String(
					"Your parcel will be delivered today",
				),
				Label: v2.String(
					"Not spam",
				),
			},
			&v2.ClassifyExample{
				Text: v2.String(
					"Review changes to our Terms and Conditions",
				),
				Label: v2.String(
					"Not spam",
				),
			},
			&v2.ClassifyExample{
				Text: v2.String(
					"Weekly sync notes",
				),
				Label: v2.String(
					"Not spam",
				),
			},
			&v2.ClassifyExample{
				Text: v2.String(
					"'Re: Follow up from today's meeting'",
				),
				Label: v2.String(
					"Not spam",
				),
			},
			&v2.ClassifyExample{
				Text: v2.String(
					"Pre-read for tomorrow",
				),
				Label: v2.String(
					"Not spam",
				),
			},
		},
		Inputs: []string{
			"Confirm your email address",
			"hey i need u to send some $",
		},
		Model: v2.String(
			"YOUR-FINE-TUNED-MODEL-ID",
		),
	}
	_, invocationErr := client.Classify(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/classify", nil, 1)
}

func TestSummarizeWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.SummarizeRequest{
		Text: `Ice cream is a sweetened frozen food typically eaten as a snack or dessert. It may be made from milk or cream and is flavoured with a sweetener, either sugar or an alternative, and a spice, such as cocoa or vanilla, or with fruit such as strawberries or peaches. It can also be made by whisking a flavored cream base and liquid nitrogen together. Food coloring is sometimes added, in addition to stabilizers. The mixture is cooled below the freezing point of water and stirred to incorporate air spaces and to prevent detectable ice crystals from forming. The result is a smooth, semi-solid foam that is solid at very low temperatures (below 2 °C or 35 °F). It becomes more malleable as its temperature increases.
            
            The meaning of the name "ice cream" varies from one country to another. In some countries, such as the United States, "ice cream" applies only to a specific variety, and most governments regulate the commercial use of the various terms according to the relative quantities of the main ingredients, notably the amount of cream. Products that do not meet the criteria to be called ice cream are sometimes labelled "frozen dairy dessert" instead. In other countries, such as Italy and Argentina, one word is used fo all variants. Analogues made from dairy alternatives, such as goat's or sheep's milk, or milk substitutes (e.g., soy, cashew, coconut, almond milk or tofu), are available for those who are lactose intolerant, allergic to dairy protein or vegan.`,
	}
	_, invocationErr := client.Summarize(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/summarize", nil, 1)
}

func TestTokenizeWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.TokenizeRequest{
		Text:  "tokenize me! :D",
		Model: "command",
	}
	_, invocationErr := client.Tokenize(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/tokenize", nil, 1)
}

func TestDetokenizeWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.DetokenizeRequest{
		Tokens: []int{
			10002,
			2261,
			2012,
			8,
			2792,
			43,
		},
		Model: "command",
	}
	_, invocationErr := client.Detokenize(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/detokenize", nil, 1)
}

func TestCheckApiKeyWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.CheckApiKey(
		context.TODO(),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/v1/check-api-key", nil, 1)
}
