// Code generated by Fern. DO NOT EDIT.

package client

import (
	os "os"

	transcriptions "github.com/cohere-ai/cohere-go/v2/audio/transcriptions"
	core "github.com/cohere-ai/cohere-go/v2/core"
	internal "github.com/cohere-ai/cohere-go/v2/internal"
)

type Client struct {
	Transcriptions *transcriptions.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.Token == "" {
		options.Token = os.Getenv("CO_API_KEY")
	}
	return &Client{
		Transcriptions: transcriptions.NewClient(options),
		options:        options,
		baseURL:        options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
