// Code generated by Fern. DO NOT EDIT.

package batches

import (
	context "context"
	v2 "github.com/cohere-ai/cohere-go/v2"
	core "github.com/cohere-ai/cohere-go/v2/core"
	internal "github.com/cohere-ai/cohere-go/v2/internal"
	option "github.com/cohere-ai/cohere-go/v2/option"
	os "os"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.Token == "" {
		options.Token = os.Getenv("CO_API_KEY")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// List the batches for the current user
func (c *Client) List(
	ctx context.Context,
	request *v2.BatchesListBatchesRequest,
	opts ...option.RequestOption,
) (*v2.ListBatchesResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates and executes a batch from an uploaded dataset of requests
func (c *Client) Create(
	ctx context.Context,
	request *v2.Batch,
	opts ...option.RequestOption,
) (*v2.CreateBatchResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves a batch
func (c *Client) Retrieve(
	ctx context.Context,
	// The batch ID.
	id string,
	opts ...option.RequestOption,
) (*v2.GetBatchResponse, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Cancels an in-progress batch
func (c *Client) Cancel(
	ctx context.Context,
	// The batch ID.
	id string,
	opts ...option.RequestOption,
) (v2.CancelBatchResponse, error) {
	response, err := c.WithRawResponse.Cancel(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
