// Code generated by Fern. DO NOT EDIT.

package connectors_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	v2 "github.com/cohere-ai/cohere-go/v2"
	client "github.com/cohere-ai/cohere-go/v2/client"
	option "github.com/cohere-ai/cohere-go/v2/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestConnectorsListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.ConnectorsListRequest{
		Limit: v2.Float64(
			1.1,
		),
		Offset: v2.Float64(
			1.1,
		),
	}
	_, invocationErr := client.Connectors.List(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestConnectorsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestConnectorsListWithWireMock", "GET", "/v1/connectors", map[string]string{"limit": "1.1", "offset": "1.1"}, 1)
}

func TestConnectorsCreateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.CreateConnectorRequest{
		Name: "name",
		Url:  "url",
	}
	_, invocationErr := client.Connectors.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestConnectorsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestConnectorsCreateWithWireMock", "POST", "/v1/connectors", nil, 1)
}

func TestConnectorsGetWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.Connectors.Get(
		context.TODO(),
		"id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestConnectorsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestConnectorsGetWithWireMock", "GET", "/v1/connectors/id", nil, 1)
}

func TestConnectorsDeleteWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.Connectors.Delete(
		context.TODO(),
		"id",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestConnectorsDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestConnectorsDeleteWithWireMock", "DELETE", "/v1/connectors/id", nil, 1)
}

func TestConnectorsUpdateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.UpdateConnectorRequest{}
	_, invocationErr := client.Connectors.Update(
		context.TODO(),
		"id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestConnectorsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestConnectorsUpdateWithWireMock", "PATCH", "/v1/connectors/id", nil, 1)
}

func TestConnectorsOAuthAuthorizeWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &v2.ConnectorsOAuthAuthorizeRequest{
		AfterTokenRedirect: v2.String(
			"after_token_redirect",
		),
	}
	_, invocationErr := client.Connectors.OAuthAuthorize(
		context.TODO(),
		"id",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestConnectorsOAuthAuthorizeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestConnectorsOAuthAuthorizeWithWireMock", "POST", "/v1/connectors/id/oauth/authorize", map[string]string{"after_token_redirect": "after_token_redirect"}, 1)
}
