name: CI
on:
  pull_request: {}
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go 1.x.x
      uses: actions/setup-go@v4
      with:
        go-version: 1.x.x
    - name: Install testing dependencies here so we dont have to edit the go.mod file
      run: |
        go get .
        go get golang.org/x/tools/go/pointer@v0.1.0-deprecated
        go get golang.org/x/sys@v0.8.0
        go get golang.org/x/tools@v0.9.2-0.20230531220058-a260315e300a
    - name: Build
      run: go build -v ./...
    - name: Setup wiremock server
      run: |
        PROJECT_NAME="wiremock-$(basename $(dirname $(pwd)) | tr -d '.')"
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
        if [ -f wiremock/docker-compose.test.yml ]; then
          docker compose -p "$PROJECT_NAME" -f wiremock/docker-compose.test.yml down
          docker compose -p "$PROJECT_NAME" -f wiremock/docker-compose.test.yml up -d
          WIREMOCK_PORT=$(docker compose -p "$PROJECT_NAME" -f wiremock/docker-compose.test.yml port wiremock 8080 | cut -d: -f2)
          echo "WIREMOCK_URL=http://localhost:$WIREMOCK_PORT" >> $GITHUB_ENV
        fi

    - name: Test
      run: go test ./...
      env:
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}

    - name: Teardown wiremock server
      if: always()
      run: |
        if [ -f wiremock/docker-compose.test.yml ]; then
          docker compose -p "$PROJECT_NAME" -f wiremock/docker-compose.test.yml down
        fi
